version: '3.1'

services:

  #DB
  mtb-db-dev:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'dev_mtb_db'
      MYSQL_USER: 'dev_mtb_db_user'
      MYSQL_PASSWORD: 'dev_mtb_db_password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'

  # Selenium-Chrome
  selenium-dev:
      image: selenium/standalone-chrome
      container_name: selenium-standalone-chrome-dev
      shm_size: 2gb
      ports:
        - '4444:4444'
        - '7900:7900'