# Это версия docker-compose.
version: '3.1'

#services: говорит о том, что все следующие строки после этого (будут сдвинуты) — относятся к сервисам, которые мы настраиваем.
# У нас такой пока только один — java-приложение под названием mtb. И уже под ним будут все его настройки.
# Например, build: context: . говорит о том, что мы будем искать Dockerfile в той же директории, что и docker-compose.yml.
services:
  mtb:
    build:
      context: .
#   Cекция environment: отвечает за то, чтобы мы передали в Dockerfile необходимые переменные среды (environment variables).
#   Как раз то, что нам и нужно. Поэтому ниже мы переменные и передаем. Их docker-compose будет искать в переменных операционной среды сервера. Добавим их в баш скрипте.
    environment:
      - BOT_NAME=${BOT_NAME}
      - BOT_TOKEN=${BOT_TOKEN}
    restart: always