version: '3.1'

#В docker-compose-test.yml будет запускаться только база данных с собственными настройками.
services:
  mtb-db-dev:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'dev_mtb_db'
      MYSQL_USER: 'dev_mtb_db_user'
      MYSQL_PASSWORD: 'dev_mtb_db_password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'