
# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: adoptopenjdk/openjdk11:ubi
    
    services:
      selenium:
        image: selenium/standalone-chrome
        options: --shm-size=2gb
        ports:
          - '4444:4444'
          - '7900:7900'
        
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '5.7'
          mysql database: 'dev_mtb_db'
          mysql root password: 'root'
          mysql user: 'dev_mtb_db_user'
          mysql password: 'dev_mtb_db_password'
          
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      
      - name: Show file content
        run: |
          ls -a
          
      - name: Create file
        run: |
          echo 'selenium.chromedriver.server.url=${{ secrets.CHROMEDRIVER_SERVER }}' > src/test/resources/application.properties
          echo 'quickpower.url=${{ secrets.QP_URL }}' >> src/test/resources/application.properties
          echo 'quickpower.login.value=${{ secrets.QP_LOGIN }}' >> src/test/resources/application.properties
          echo 'quickpower.password.value=${{ secrets.QP_PWD }}' >> src/test/resources/application.properties
          
      - name: Show file content
        run: |
          ls -a
          
      - name: Starting Selenoid Server (aerokube/selenoid) within actions
        # You may pin to the exact commit or the version.
        # uses: ajinx/selenoid@a717ac4e12ebad3b3cc8ca5c584fe57ff1a9460b
        uses: ajinx/selenoid@2.0
          
      - name: Build with Maven
        run: |
          export TG_MTB_DB_USERNAME=${{ secrets.TG_MTB_DB_USERNAME }}
          export TG_MTB_DB_PASSWORD=${{ secrets.TG_MTB_DB_PASSWORD }}
          export TG_MTB_TOKEN=${{ secrets.TG_MTB_TOKEN }}
          export TG_MTB_USERNAME=${{ secrets.TG_MTB_USERNAME }}
          mvn -B package --file pom.xml
